### ISSUE TITLE
Research Github Activity Api

### ISSUE THREAD

**Issue by karleenmsrichards** [BoshraM/Readme-Hireme#3]
As a developer I want to find out how can I get contributions, projects and skills from Github API so I can plan my next step for the UI/UX Design.

**Comment by BoshraM** [comment]
we can information listed below from this API :[https://api.github.com/users/[USERNAME]](url):
GitHub user name
github imagel
gitHub link
followers/following
starred project: https://api.github.com/users/USERNAME/starred  ===> which we can get language used and demo link
organisations
url for all the  all the repo 
name
company
blog
location
email
hireable
bio
twitter_username
